---
# Playbook to install sphinx search
- name: Install sphinx search
  apt: name=sphinxsearch state=present force=yes
- name: Remove cron job for daily indexing from /etc/cron.d
  cron: cron_file=sphinxsearch state=absent
- name: Copy init.d script to system-wide location
  template: src=sphinxsearch dest=/etc/init.d/sphinxsearch mode=755