---
# Tasks create the database and import sentences in it

- name: Delete old database with same name if it exists
  shell: echo "DROP DATABASE IF EXISTS {{mysql_db_name}}" | mysql -u {{mysql_user}} -p{{mysql_password}}
- name: Create a new mysql database
  shell: echo "CREATE DATABASE {{mysql_db_name}}" | mysql -u {{mysql_user}} -p{{mysql_password}}
- name: Initialize {{mysql_db_name}} with empty tables
  shell: mysql -u {{mysql_user}} -p{{mysql_password}} {{mysql_db_name}} < /var/www-prod/docs/database/{{item}}
  with_items:
  - database_20130406.sql
  - import/groups.sql
  - import/users.sql
  - import/acos.sql
  - import/aros.sql
  - import/aros_acos.sql
  - import/countries.sql
- name: Install updates
  script: install_updates.sh {{mysql_user}} {{mysql_password}} {{mysql_db_name}} {{code_dir}}/versions/current/docs/database/updates/
- name: Copy csv's to /tmp folder
  copy: src={{item}} dest=/tmp/{{item}} mode=777 owner=mysql group=mysql
  with_items:
  - sentences.csv
  - links.csv
  - tag_metadata.csv
  - tags_detailed.csv
  when: download_csv == false
- name: Download csv's from http://tatoeba.org/files/downloads/
  get_url: url=http://tatoeba.org/files/downloads/{{item}} dest=/tmp/{{item}} mode=777 owner=mysql group=mysql
  with_items:
  - sentences.csv
  - links.csv
  - tag_metadata.csv
  - tags_detailed.csv
  when: download_csv == true
- name: Import sentences in the tatoeba database
  shell: mysql -u {{mysql_user}} -p{{mysql_password}} {{mysql_db_name}} < /var/www-prod/docs/database/import/restore_dumps.sql
