---
#Tasks for setting up php5

- name: Install php5
  apt: name={{ item }} update_cache=yes cache_valid_time=36000 state=present
  with_items:
  - php5-fpm
  - php5-cli
  - php5-mysql
  - php5-intl
  - php5-curl
  - php5-memcache
  - php5-imagick
  - php5-mcrypt
  - memcached

- name: Copy php configuration files
  copy: src=php.conf dest=/etc/php5/fpm/pool.d/tatoeba.conf

- name: Restart nginx
  service: name=nginx state=restarted enabled=yes
- name: Restart php5-fpm
  service: name=php5-fpm state=restarted enabled=yes
