---
# Tasks specyfing commom tasks for all servers

- name: Ensure git is installed
  apt:
    name: git
    state: latest
    force: yes

- name: Install localization tools
  apt:
    name: [ 'gettext', 'transifex-client' ]
  when: deploy_for == 'dev'
