---
# Tasks to install New Relic plugin agent to monitor php-fpm and nginx

- name: Install newrelic plugin agent
  pip: name=newrelic-plugin-agent state=present

- { include: ../../setup_nginx/tasks/main.yml, enable_status_pages: true }

- name: Copy newrelic-plugin-agent configuration file
  template: src=newrelic-plugin-agent.cfg dest=/etc/newrelic/newrelic-plugin-agent.cfg owner=newrelic group=newrelic mode=0644
- name: Copy the init.d script
  copy: src=newrelic-plugin-agent dest=/etc/init.d/newrelic-plugin-agent owner=root group=root mode=0755
- name: Start the monitoring daemon
  service: name=newrelic-plugin-agent state=restarted