---
#Playbook to configure sphinx and create indexes

- hosts: all
  become: true
  gather_facts: yes
  pre_tasks:
  - name: Clean the index directory
    command: rm -rf {{sphinx_index_dir}}
  roles:
  - { role: configure_sphinx, sphinx_create_indexes: true }
