---
# Playbook to install sphinx search
- name: Install sphinx search
  apt: name=sphinxsearch state=present force=yes
- name: Remove cron job for daily indexing from /etc/cron.d
  cron: name="" cron_file=sphinxsearch state=absent
- name: Set the location of pid file in Sphinx's init.d script
  command: sed -i 's|^PIDFILE=.*|PIDFILE={{sphinx_pid_file}}|' /etc/init.d/sphinxsearch
- name: Set the location of log directory in Sphinx's init.d script
  command: sed -i 's|^LOGDIR=.*|LOGDIR={{sphinx_log_dir}}|' /etc/init.d/sphinxsearch